version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: estoque
      POSTGRES_USER: estoque
      POSTGRES_PASSWORD: estoque
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts/initial.sql:/docker-entrypoint-initdb.d/1-init.sql

